Made it compatible with the new composition api
tserkov/vue-plugin-load-script pull request #20
Opened 2020-09-24 19:34 UTC by Bjornar97

Exports the functions loadScript and unloadScript, so they can be used directly by importing them. The previous behavior of using this.loadScript still works.

Feel free to make any changes you see fit.

2020-09-24 19:47 UTC, Bjornar97 commented
The reason for exporting the functions btw, is that "this" is not available inside the setup function in components.

2021-04-20 20:04 UTC, Bjornar97 commented
Hi. Is there an update on getting this merged available?

2021-04-27 23:06 UTC, tserkov requested changes
Hey @Bjornar97! Sorry for _incredible_ delay! I've made a few minor requests to the code, and after they're made I'll smash that merge button.

Thanks for taking care of Composition API support!

2021-04-27 23:06 UTC, tserkov commented on index.js
> +function loadScript(src) {
It looks like your editor's formatter went a little crazy -- please fix the indentation.

2021-04-27 23:06 UTC, tserkov commented on index.js
> +const thisLoadScript = {
I think `plugin` would work better than `thisLoadScript`.

2021-05-30 18:26 UTC, merged

2021-05-30 18:27 UTC, tserkov commented
Lgtm, thanks again!